# ==== Site metadata ====
title: "Aadil Ali — Portfolio"
description: "Digital transformation, AI integration, and strategy."
lang: en
og_image: "assets/profile.jpg"

# Public URL for GitHub Pages (user/org site lives at the root)
url: "https://aaadil777.github.io"
baseurl: ""   # keep empty for user/organization pages

# Contact / social (used in templates & SEO)
email: "your-email@example.com"
linkedin: "https://www.linkedin.com/in/aadil-ali01"
github: "https://github.com/aaadil777"
calendar: "https://calendar.google.com/calendar/u/0/appointments/schedules/AcZssZ1bdsyGyWYywDzVKcUeWpQteRkzItjo292s6fmdwFW3MnvtrE-g4UgDKx-FBeVXYlooG8_hzJSM"
resume_url: "https://drive.google.com/file/d/1JfynHbI1yvtBb6x_Bwq6HZEJpXT6x4sK/view?usp=sharing"

# Optional: helps jekyll-seo-tag find your profiles
social:
  links:
    - "https://www.linkedin.com/in/aadil-ali01"
    - "https://github.com/aaadil777"

# ==== Build & plugins ====
theme: minima   # harmless even with custom layouts; remove if you want
plugins:
  - jekyll-seo-tag
  - jekyll-feed

markdown: kramdown
kramdown:
  input: GFM
permalink: pretty

# Default front matter (so pages render with your layout unless overridden)
defaults:
  - scope:
      path: ""
    values:
      layout: default

# ==== Excludes (won’t be processed/published) ====
exclude:
  - node_modules/
  - vendor/
  - .gitignore
  - README.md
  - package.json
  - package-lock.json
  - yarn.lock
  - webpack.config.js
