# === Site metadata ===
title: "Aadil Ali — Digital Transformation, AI Integration, Strategy"
email: aadilali0630@gmail.com
description: >-
  Portfolio and contact hub for Aadil Ali — focused on digital transformation,
  AI integration, and strategy across product, supply chain, and analytics.

# For a user/organization site, baseurl stays empty.
baseurl: ""                         # e.g. "/blog" for project sites
url: "https://aaadil777.github.io"  # your live site

# === Build settings ===
# Disable the bundled Minima theme so your custom CSS/JS take effect.
theme: null

# Use your default layout for all pages and posts
defaults:
  - scope:
      path: ""
    values:
      layout: default

# Markdown/Permalinks (optional but sensible)
markdown: kramdown
permalink: pretty

# Plugins that GitHub Pages supports
plugins:
  - jekyll-seo-tag
  - jekyll-feed
linkedin: "https://www.linkedin.com/in/aadil-ali01"
github: "https://github.com/aaadil777"
calendar: "https://calendar.google.com/calendar/u/0/appointments/schedules/AcZssZ1bdsyGyWYywDzVKcUeWpQteRkzItjo292s6fmdwFW3MnvtrE-g4UgDKx-FBeVXYlooG8_hzJSM"
resume_url: "https://drive.google.com/file/d/1JfynHbI1yvtBb6x_Bwq6HZEJpXT6x4sK/view?usp=sharing"
# Files/dirs Jekyll shouldn’t process
exclude:
  - README.md
  - node_modules/
  - vendor/
  - .gitignore
  - Gemfile
  - Gemfile.lock
